<script setup>
import { computed } from 'vue'
import { useUploadStore } from '../stores/uploadStore'
const upload = useUploadStore()
const arquivo = computed(() => upload.arquivo?.name || 'Nenhuma planilha processada')
</script>

<template>
  <main class="page-lines min-h-screen bg-[#0d0f10] px-5 py-8 text-[#e9e7df] lg:px-8"><div class="mx-auto max-w-7xl">
    <header class="mb-9 flex flex-col justify-between gap-5 border-b border-white/[.1] pb-6 md:flex-row md:items-end"><div><p class="text-[10px] font-bold uppercase tracking-[.18em] text-[#b7df9c]">Controle de qualidade</p><h1 class="mt-2 text-3xl font-semibold tracking-[-.035em]">Relatório de validação</h1><p class="mt-2 text-sm text-[#919a95]">Arquivo: <span class="text-[#d9ddd5]">{{ arquivo }}</span></p></div><router-link to="/upload" class="border border-[#6fae55] px-4 py-2.5 text-sm font-bold text-[#b7df9c] transition hover:bg-[#6fae55] hover:text-[#101411]">Nova importação</router-link></header>
    <template v-if="upload.temResultado">
      <section class="grid gap-px border border-white/[.1] bg-white/[.1] sm:grid-cols-2 xl:grid-cols-4"><article class="bg-[#151819] p-5"><p class="text-[10px] font-bold uppercase tracking-[.14em] text-[#75807b]">Total</p><p class="mt-4 text-3xl font-semibold">{{ upload.totalRegistros }}</p></article><article class="bg-[#151819] p-5"><p class="text-[10px] font-bold uppercase tracking-[.14em] text-[#75807b]">Válidos</p><p class="mt-4 text-3xl font-semibold text-[#b7df9c]">{{ upload.registrosValidos }}</p></article><article class="bg-[#151819] p-5"><p class="text-[10px] font-bold uppercase tracking-[.14em] text-[#75807b]">Com erro</p><p class="mt-4 text-3xl font-semibold text-[#91c773]">{{ upload.registrosComErro }}</p></article><article class="bg-[#151819] p-5"><p class="text-[10px] font-bold uppercase tracking-[.14em] text-[#75807b]">Ocorrências</p><p class="mt-4 text-3xl font-semibold">{{ upload.totalErros }}</p></article></section>
      <section class="mt-6 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><article class="border border-white/[.1] bg-[#151819] p-6"><p class="text-[10px] font-bold uppercase tracking-[.14em] text-[#b7df9c]">Resumo</p><h2 class="mt-1 text-lg font-semibold">Erros por tipo</h2><div v-if="upload.errosPorTipo.length" class="mt-6 divide-y divide-white/[.08] border-y border-white/[.08]"><div v-for="item in upload.errosPorTipo" :key="item.tipo" class="flex justify-between gap-4 py-4 text-sm"><span class="text-[#bfc6bf]">{{ item.tipo }}</span><b class="text-[#b7df9c]">{{ item.total }}</b></div></div><p v-else class="mt-6 border-l-2 border-[#6fae55] bg-white/[.03] p-4 text-sm text-[#b7df9c]">Nenhum erro encontrado.</p></article>
      <article class="overflow-hidden border border-white/[.1] bg-[#151819]"><div class="border-b border-white/[.08] p-6"><p class="text-[10px] font-bold uppercase tracking-[.14em] text-[#b7df9c]">Detalhamento</p><h2 class="mt-1 text-lg font-semibold">Ocorrências da planilha</h2></div><div v-if="upload.erros.length" class="overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-[#101313] text-[10px] uppercase tracking-[.12em] text-[#75807b]"><tr><th class="px-5 py-4">Linha</th><th class="px-5 py-4">Campo</th><th class="px-5 py-4">Tipo</th><th class="px-5 py-4">Descrição</th></tr></thead><tbody><tr v-for="erro in upload.erros" :key="erro.id" class="border-t border-white/[.07]"><td class="px-5 py-4 font-bold text-[#b7df9c]">{{ erro.linha }}</td><td class="px-5 py-4 text-[#dce0d8]">{{ erro.campo }}</td><td class="px-5 py-4 text-[#9dcf87]">{{ erro.tipo }}</td><td class="px-5 py-4 text-[#89928d]">{{ erro.descricao }}</td></tr></tbody></table></div><p v-else class="p-6 text-sm text-[#b7df9c]">A planilha foi aprovada sem pendências.</p></article></section>
    </template>
    <section v-else class="border border-white/[.1] bg-[#151819] p-12 text-center"><p class="text-lg font-semibold">Ainda não há relatório para exibir.</p><p class="mt-2 text-sm text-[#89928d]">Importe uma planilha e inicie a validação.</p><router-link to="/upload" class="mt-6 inline-block bg-[#6fae55] px-5 py-3 text-sm font-bold text-[#101411]">Ir para importação</router-link></section>
  </div></main>
</template>
